// <auto-generated />
using System;
using Cugger.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cugger.Migrations
{
    [DbContext(typeof(CuggerDbContext))]
    [Migration("20260709180025_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Cugger.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            AvatarUrl = "https://ui-avatars.com/api/?name=Dragan+Maric&background=F59E0B&color=fff",
                            Bio = "Apsolvent pivarstva i ljubitelj kvalitetnih piva",
                            ConcurrencyStamp = "c0000000-0000-0000-0000-000000000001",
                            Email = "dragan@example.com",
                            EmailConfirmed = true,
                            FirstName = "Dragan",
                            LastName = "Marić",
                            LockoutEnabled = true,
                            NormalizedEmail = "DRAGAN@EXAMPLE.COM",
                            NormalizedUserName = "PIVO_LOVER",
                            PasswordHash = "SEED_NEEDS_HASH",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "b0000000-0000-0000-0000-000000000001",
                            TwoFactorEnabled = false,
                            UserName = "pivo_lover"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            AvatarUrl = "https://ui-avatars.com/api/?name=Marko+Horvat&background=D97706&color=fff",
                            Bio = "IPA entuzijast, traži nove craft pivovare",
                            ConcurrencyStamp = "c0000000-0000-0000-0000-000000000002",
                            Email = "marko@example.com",
                            EmailConfirmed = true,
                            FirstName = "Marko",
                            LastName = "Horvat",
                            LockoutEnabled = true,
                            NormalizedEmail = "MARKO@EXAMPLE.COM",
                            NormalizedUserName = "HOP_KING",
                            PasswordHash = "SEED_NEEDS_HASH",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "b0000000-0000-0000-0000-000000000002",
                            TwoFactorEnabled = false,
                            UserName = "hop_king"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            AvatarUrl = "https://ui-avatars.com/api/?name=Ana+Novak&background=FCD34D&color=111",
                            Bio = "Ljubiteljica tamnih piva i europskih pivovara",
                            ConcurrencyStamp = "c0000000-0000-0000-0000-000000000003",
                            Email = "ana@example.com",
                            EmailConfirmed = true,
                            FirstName = "Ana",
                            LastName = "Novak",
                            LockoutEnabled = true,
                            NormalizedEmail = "ANA@EXAMPLE.COM",
                            NormalizedUserName = "STOUT_FAN",
                            PasswordHash = "SEED_NEEDS_HASH",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "b0000000-0000-0000-0000-000000000003",
                            TwoFactorEnabled = false,
                            UserName = "stout_fan"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            AvatarUrl = "https://ui-avatars.com/api/?name=Luka+Kovac&background=A16207&color=fff",
                            Bio = "Putujem svijetom u potrazi za savršenim pivom",
                            ConcurrencyStamp = "c0000000-0000-0000-0000-000000000004",
                            Email = "luka@example.com",
                            EmailConfirmed = true,
                            FirstName = "Luka",
                            LastName = "Kovač",
                            LockoutEnabled = true,
                            NormalizedEmail = "LUKA@EXAMPLE.COM",
                            NormalizedUserName = "CRAFT_EXPLORER",
                            PasswordHash = "SEED_NEEDS_HASH",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "b0000000-0000-0000-0000-000000000004",
                            TwoFactorEnabled = false,
                            UserName = "craft_explorer"
                        });
                });

            modelBuilder.Entity("Cugger.Models.Beer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ABV")
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("BreweryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("IBU")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Style")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BreweryId");

                    b.ToTable("Beers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ABV = 5.1m,
                            BreweryId = 1,
                            Description = "Klasično hrvatsko lager pivo",
                            IBU = 20,
                            ImageUrl = "",
                            Name = "Karlovačko",
                            Style = 0
                        },
                        new
                        {
                            Id = 2,
                            ABV = 6.9m,
                            BreweryId = 2,
                            Description = "Aromatično IPA pivo s bogatom gorčinom",
                            IBU = 77,
                            ImageUrl = "",
                            Name = "Stone IPA",
                            Style = 2
                        },
                        new
                        {
                            Id = 3,
                            ABV = 4.3m,
                            BreweryId = 3,
                            Description = "Klasični Guinness Stout s karakterističnom tamnom bojom",
                            IBU = 45,
                            ImageUrl = "",
                            Name = "Guinness Extra Stout",
                            Style = 3
                        },
                        new
                        {
                            Id = 4,
                            ABV = 5m,
                            BreweryId = 1,
                            Description = "Premium belgijsko pilsner pivo",
                            IBU = 30,
                            ImageUrl = "",
                            Name = "Stella Artois",
                            Style = 1
                        },
                        new
                        {
                            Id = 5,
                            ABV = 7.7m,
                            BreweryId = 2,
                            Description = "Ekstremno hopna IPA s intenzivnom gorčinom",
                            IBU = 100,
                            ImageUrl = "",
                            Name = "Stone Ruination",
                            Style = 2
                        },
                        new
                        {
                            Id = 6,
                            ABV = 5.2m,
                            BreweryId = 4,
                            Description = "Zmajska Pale Ale - hrvatski craft klasik",
                            IBU = 35,
                            ImageUrl = "",
                            Name = "Pale Ale",
                            Style = 5
                        },
                        new
                        {
                            Id = 7,
                            ABV = 5.6m,
                            BreweryId = 5,
                            Description = "Trans-atlantska post-punk IPA",
                            IBU = 40,
                            ImageUrl = "",
                            Name = "Punk IPA",
                            Style = 2
                        },
                        new
                        {
                            Id = 8,
                            ABV = 4.8m,
                            BreweryId = 4,
                            Description = "Tradicionalno pšenično pivo s notama citrusa",
                            IBU = 12,
                            ImageUrl = "",
                            Name = "Pšenica",
                            Style = 6
                        });
                });

            modelBuilder.Entity("Cugger.Models.BeerPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BeerId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("varchar(260)");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("varchar(260)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeerId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("BeerPhotos");
                });

            modelBuilder.Entity("Cugger.Models.Brewery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("FoundedYear")
                        .HasColumnType("int");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Breweries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Karlovac",
                            Country = "Hrvatska",
                            Description = "Najstarija pivovara u Hrvatskoj",
                            FoundedYear = 1854,
                            LogoUrl = "",
                            Name = "Karlovačka Pivovara",
                            WebsiteUrl = "https://www.karlovacka.hr"
                        },
                        new
                        {
                            Id = 2,
                            City = "San Diego",
                            Country = "SAD",
                            Description = "Poznata za svoje IPA piva",
                            FoundedYear = 1996,
                            LogoUrl = "",
                            Name = "Stone Brewing",
                            WebsiteUrl = "https://www.stonebrewing.com"
                        },
                        new
                        {
                            Id = 3,
                            City = "Dublin",
                            Country = "Irska",
                            Description = "Legendarni proizvođač Guinness piva",
                            FoundedYear = 1759,
                            LogoUrl = "",
                            Name = "Guinness Brewery",
                            WebsiteUrl = "https://www.guinness.com"
                        },
                        new
                        {
                            Id = 4,
                            City = "Zagreb",
                            Country = "Hrvatska",
                            Description = "Hrvatska craft pivovara s karakterom",
                            FoundedYear = 2014,
                            LogoUrl = "",
                            Name = "Zmajska Pivovara",
                            WebsiteUrl = "https://zmajska.hr"
                        },
                        new
                        {
                            Id = 5,
                            City = "Ellon",
                            Country = "Škotska",
                            Description = "Punk craft revolucija iz Škotske",
                            FoundedYear = 2007,
                            LogoUrl = "",
                            Name = "BrewDog",
                            WebsiteUrl = "https://brewdog.com"
                        });
                });

            modelBuilder.Entity("Cugger.Models.CheckIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BeerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeerId");

                    b.HasIndex("UserId");

                    b.HasIndex("VenueId");

                    b.ToTable("CheckIns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BeerId = 1,
                            CheckInDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comment = "Odličan izbor za topli dan",
                            CreatedAt = new DateTime(2024, 3, 15, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4m,
                            UserId = 1,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 2,
                            BeerId = 2,
                            CheckInDate = new DateTime(2024, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comment = "Sjajna IPA, preporučujem svima",
                            CreatedAt = new DateTime(2024, 3, 16, 20, 15, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4.5m,
                            UserId = 1,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 3,
                            BeerId = 2,
                            CheckInDate = new DateTime(2024, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comment = "Savršeno! Najbolja IPA koju sam pio",
                            CreatedAt = new DateTime(2024, 3, 17, 21, 45, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5m,
                            UserId = 2,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 4,
                            BeerId = 5,
                            CheckInDate = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comment = "Jako hopno, za prave IPA ljubitelje",
                            CreatedAt = new DateTime(2024, 3, 18, 19, 20, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4m,
                            UserId = 2,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 5,
                            BeerId = 3,
                            CheckInDate = new DateTime(2024, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comment = "Pravi Guinness u Dublinu - nema boljeg!",
                            CreatedAt = new DateTime(2024, 3, 19, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5m,
                            UserId = 3,
                            VenueId = 3
                        },
                        new
                        {
                            Id = 6,
                            BeerId = 1,
                            CheckInDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comment = "Dobro hrvatsko pivo, čvrst izbor",
                            CreatedAt = new DateTime(2024, 3, 20, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3.5m,
                            UserId = 3,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 7,
                            BeerId = 3,
                            CheckInDate = new DateTime(2024, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comment = "Klasičan Stout, topla preporuka",
                            CreatedAt = new DateTime(2024, 3, 21, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4.5m,
                            UserId = 1,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 8,
                            BeerId = 6,
                            CheckInDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comment = "Hrvatski craft je stvarno došao daleko",
                            CreatedAt = new DateTime(2024, 4, 5, 21, 10, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4.5m,
                            UserId = 4,
                            VenueId = 4
                        },
                        new
                        {
                            Id = 9,
                            BeerId = 7,
                            CheckInDate = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comment = "Punk attitude u svakom gutljaju",
                            CreatedAt = new DateTime(2024, 4, 12, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4m,
                            UserId = 4,
                            VenueId = 5
                        },
                        new
                        {
                            Id = 10,
                            BeerId = 8,
                            CheckInDate = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comment = "Osvježavajuće, za ljetni dan",
                            CreatedAt = new DateTime(2024, 4, 20, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3.5m,
                            UserId = 2,
                            VenueId = 4
                        });
                });

            modelBuilder.Entity("Cugger.Models.Friendship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FromUserId")
                        .HasColumnType("int");

                    b.Property<int>("ToUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("Friendships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromUserId = 1,
                            ToUserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromUserId = 2,
                            ToUserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromUserId = 1,
                            ToUserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromUserId = 2,
                            ToUserId = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromUserId = 4,
                            ToUserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromUserId = 1,
                            ToUserId = 4
                        });
                });

            modelBuilder.Entity("Cugger.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BeerId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeerId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BeerId = 2,
                            Comment = "Odličan balans između gorčine i arome",
                            CreatedAt = new DateTime(2024, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Likes = 12,
                            Rating = 4.5m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BeerId = 2,
                            Comment = "Jedna od najboljih IPA-a koju sam ikad probao",
                            CreatedAt = new DateTime(2024, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Likes = 23,
                            Rating = 5m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            BeerId = 3,
                            Comment = "Irski stout kakav treba biti",
                            CreatedAt = new DateTime(2024, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Likes = 18,
                            Rating = 5m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            BeerId = 6,
                            Comment = "Zmajska zna što radi - svaka čast.",
                            CreatedAt = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Likes = 9,
                            Rating = 4.5m,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Cugger.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ulica 1, broj 10",
                            City = "Zagreb",
                            Country = "Hrvatska",
                            Latitude = 45.815m,
                            Longitude = 15.982m,
                            Name = "The Beer Garden"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Ilica 25",
                            City = "Zagreb",
                            Country = "Hrvatska",
                            Latitude = 45.816m,
                            Longitude = 15.985m,
                            Name = "Craft Beer Pub"
                        },
                        new
                        {
                            Id = 3,
                            Address = "O'Connell Street, broj 1",
                            City = "Dublin",
                            Country = "Irska",
                            Latitude = 53.349m,
                            Longitude = -6.26m,
                            Name = "Irish Pub Dublin"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Tkalčićeva 36",
                            City = "Zagreb",
                            Country = "Hrvatska",
                            Latitude = 45.815m,
                            Longitude = 15.978m,
                            Name = "Mali Medo"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Ulica grada Vukovara 269",
                            City = "Zagreb",
                            Country = "Hrvatska",
                            Latitude = 45.798m,
                            Longitude = 15.989m,
                            Name = "Pivnica Pinta"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "a0000000-0000-0000-0000-000000000001",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "a0000000-0000-0000-0000-000000000002",
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Cugger.Models.Beer", b =>
                {
                    b.HasOne("Cugger.Models.Brewery", "Brewery")
                        .WithMany("Beers")
                        .HasForeignKey("BreweryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brewery");
                });

            modelBuilder.Entity("Cugger.Models.BeerPhoto", b =>
                {
                    b.HasOne("Cugger.Models.Beer", "Beer")
                        .WithMany("Photos")
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cugger.Models.AppUser", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Beer");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Cugger.Models.CheckIn", b =>
                {
                    b.HasOne("Cugger.Models.Beer", "Beer")
                        .WithMany("CheckIns")
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cugger.Models.AppUser", "User")
                        .WithMany("CheckIns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cugger.Models.Venue", "Venue")
                        .WithMany("CheckIns")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Beer");

                    b.Navigation("User");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Cugger.Models.Friendship", b =>
                {
                    b.HasOne("Cugger.Models.AppUser", "FromUser")
                        .WithMany("FromFriendships")
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cugger.Models.AppUser", "ToUser")
                        .WithMany("ToFriendships")
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("Cugger.Models.Review", b =>
                {
                    b.HasOne("Cugger.Models.Beer", "Beer")
                        .WithMany("Reviews")
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cugger.Models.AppUser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Beer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Cugger.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Cugger.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cugger.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Cugger.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cugger.Models.AppUser", b =>
                {
                    b.Navigation("CheckIns");

                    b.Navigation("FromFriendships");

                    b.Navigation("Reviews");

                    b.Navigation("ToFriendships");
                });

            modelBuilder.Entity("Cugger.Models.Beer", b =>
                {
                    b.Navigation("CheckIns");

                    b.Navigation("Photos");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Cugger.Models.Brewery", b =>
                {
                    b.Navigation("Beers");
                });

            modelBuilder.Entity("Cugger.Models.Venue", b =>
                {
                    b.Navigation("CheckIns");
                });
#pragma warning restore 612, 618
        }
    }
}
