// <auto-generated />
using System;
using Cugger.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cugger.Migrations
{
    [DbContext(typeof(CuggerDbContext))]
    [Migration("20260507075528_AddUserAuth")]
    partial class AddUserAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Cugger.Models.Beer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ABV")
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("BreweryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("IBU")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Style")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BreweryId");

                    b.ToTable("Beers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ABV = 5.0999999999999996,
                            BreweryId = 1,
                            Description = "Klasično hrvatsko lager pivo",
                            IBU = 20,
                            ImageUrl = "",
                            Name = "Karlovačko",
                            Style = 0
                        },
                        new
                        {
                            Id = 2,
                            ABV = 6.9000000000000004,
                            BreweryId = 2,
                            Description = "Aromatično IPA pivo s bogatom gorčinom",
                            IBU = 77,
                            ImageUrl = "",
                            Name = "Stone IPA",
                            Style = 2
                        },
                        new
                        {
                            Id = 3,
                            ABV = 4.2999999999999998,
                            BreweryId = 3,
                            Description = "Klasični Guinness Stout sa karakterističnom tamnom bojom",
                            IBU = 45,
                            ImageUrl = "",
                            Name = "Guinness Extra Stout",
                            Style = 3
                        },
                        new
                        {
                            Id = 4,
                            ABV = 5.0,
                            BreweryId = 1,
                            Description = "Premium belgijsko pilsner pivo",
                            IBU = 30,
                            ImageUrl = "",
                            Name = "Stella Artois",
                            Style = 1
                        },
                        new
                        {
                            Id = 5,
                            ABV = 7.7000000000000002,
                            BreweryId = 2,
                            Description = "Ekstremno hopno IPA s intenzivnom gorčinom",
                            IBU = 100,
                            ImageUrl = "",
                            Name = "Stone Ruination",
                            Style = 2
                        },
                        new
                        {
                            Id = 6,
                            ABV = 5.2000000000000002,
                            BreweryId = 4,
                            Description = "Zmajska Pale Ale - hrvatski craft klasik",
                            IBU = 35,
                            ImageUrl = "",
                            Name = "Pale Ale",
                            Style = 5
                        },
                        new
                        {
                            Id = 7,
                            ABV = 5.5999999999999996,
                            BreweryId = 5,
                            Description = "Trans-atlantska post-punk IPA",
                            IBU = 40,
                            ImageUrl = "",
                            Name = "Punk IPA",
                            Style = 2
                        },
                        new
                        {
                            Id = 8,
                            ABV = 4.7999999999999998,
                            BreweryId = 4,
                            Description = "Tradicionalno pšenično pivo s notama citrusa",
                            IBU = 12,
                            ImageUrl = "",
                            Name = "Pšenica",
                            Style = 6
                        });
                });

            modelBuilder.Entity("Cugger.Models.Brewery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("FoundedYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Breweries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Karlovac",
                            Country = "Hrvatska",
                            Description = "Najstarija pivovara u Hrvatskoj",
                            FoundedYear = 1854,
                            LogoUrl = "",
                            Name = "Karlovačka Pivovara",
                            WebsiteUrl = "https://www.karlovacka.hr"
                        },
                        new
                        {
                            Id = 2,
                            City = "San Diego",
                            Country = "SAD",
                            Description = "Poznata za svoje IPA piva",
                            FoundedYear = 1996,
                            LogoUrl = "",
                            Name = "Stone Brewing",
                            WebsiteUrl = "https://www.stonebrewing.com"
                        },
                        new
                        {
                            Id = 3,
                            City = "Dublin",
                            Country = "Irska",
                            Description = "Legendarni proizvođač Guinnessa",
                            FoundedYear = 1759,
                            LogoUrl = "",
                            Name = "Guinness Brewery",
                            WebsiteUrl = "https://www.guinness.com"
                        },
                        new
                        {
                            Id = 4,
                            City = "Zagreb",
                            Country = "Hrvatska",
                            Description = "Hrvatska craft pivovara s karakterom",
                            FoundedYear = 2014,
                            LogoUrl = "",
                            Name = "Zmajska Pivovara",
                            WebsiteUrl = "https://zmajska.hr"
                        },
                        new
                        {
                            Id = 5,
                            City = "Ellon",
                            Country = "Škotska",
                            Description = "Punk craft revolucija iz Škotske",
                            FoundedYear = 2007,
                            LogoUrl = "",
                            Name = "BrewDog",
                            WebsiteUrl = "https://brewdog.com"
                        });
                });

            modelBuilder.Entity("Cugger.Models.CheckIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VenueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BeerId");

                    b.HasIndex("UserId");

                    b.HasIndex("VenueId");

                    b.ToTable("CheckIns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BeerId = 1,
                            CheckInDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comment = "Odličan izbor za topli dan",
                            CreatedAt = new DateTime(2024, 3, 15, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4.0,
                            UserId = 1,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 2,
                            BeerId = 2,
                            CheckInDate = new DateTime(2024, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comment = "Sjajna IPA, preporučujem svima",
                            CreatedAt = new DateTime(2024, 3, 16, 20, 15, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4.5,
                            UserId = 1,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 3,
                            BeerId = 2,
                            CheckInDate = new DateTime(2024, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comment = "Savršeno! Najbolja IPA koju sam pio",
                            CreatedAt = new DateTime(2024, 3, 17, 21, 45, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5.0,
                            UserId = 2,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 4,
                            BeerId = 5,
                            CheckInDate = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comment = "Jako hopno, za prave IPA ljubitelje",
                            CreatedAt = new DateTime(2024, 3, 18, 19, 20, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4.0,
                            UserId = 2,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 5,
                            BeerId = 3,
                            CheckInDate = new DateTime(2024, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comment = "Pravi Guinness u Dublinu - nema boljeg!",
                            CreatedAt = new DateTime(2024, 3, 19, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5.0,
                            UserId = 3,
                            VenueId = 3
                        },
                        new
                        {
                            Id = 6,
                            BeerId = 1,
                            CheckInDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comment = "Dobro hrvatsko pivo, čvrst izbor",
                            CreatedAt = new DateTime(2024, 3, 20, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3.5,
                            UserId = 3,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 7,
                            BeerId = 3,
                            CheckInDate = new DateTime(2024, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comment = "Klasičan Stout, topla preporuka",
                            CreatedAt = new DateTime(2024, 3, 21, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4.5,
                            UserId = 1,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 8,
                            BeerId = 6,
                            CheckInDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comment = "Hrvatski craft je stvarno došao daleko",
                            CreatedAt = new DateTime(2024, 4, 5, 21, 10, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4.5,
                            UserId = 4,
                            VenueId = 4
                        },
                        new
                        {
                            Id = 9,
                            BeerId = 7,
                            CheckInDate = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comment = "Punk attitude u svakom gutljaju",
                            CreatedAt = new DateTime(2024, 4, 12, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4.0,
                            UserId = 4,
                            VenueId = 5
                        },
                        new
                        {
                            Id = 10,
                            BeerId = 8,
                            CheckInDate = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comment = "Osvježavajuće, za ljetni dan",
                            CreatedAt = new DateTime(2024, 4, 20, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3.5,
                            UserId = 2,
                            VenueId = 4
                        });
                });

            modelBuilder.Entity("Cugger.Models.Friendship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FromUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("Friendships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromUserId = 1,
                            ToUserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromUserId = 2,
                            ToUserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromUserId = 1,
                            ToUserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromUserId = 2,
                            ToUserId = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromUserId = 4,
                            ToUserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromUserId = 1,
                            ToUserId = 4
                        });
                });

            modelBuilder.Entity("Cugger.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Likes")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Rating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BeerId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BeerId = 2,
                            Comment = "Odličan balans između gorčine i arome",
                            CreatedAt = new DateTime(2024, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Likes = 12,
                            Rating = 4.5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BeerId = 2,
                            Comment = "Jedna od najboljih IPA-a koju sam ikad probao",
                            CreatedAt = new DateTime(2024, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Likes = 23,
                            Rating = 5.0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            BeerId = 3,
                            Comment = "Irski stout kakav treba biti",
                            CreatedAt = new DateTime(2024, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Likes = 18,
                            Rating = 5.0,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            BeerId = 6,
                            Comment = "Zmajska zna što radi - svaka čast.",
                            CreatedAt = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Likes = 9,
                            Rating = 4.5,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Cugger.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarUrl = "https://ui-avatars.com/api/?name=Dragan+Maric&background=F59E0B&color=fff",
                            Bio = "Apsolventist pivarstva i ljubitelj kvalitetnih piva",
                            Email = "dragan@example.com",
                            FirstName = "Dragan",
                            LastName = "Marić",
                            PasswordHash = "SEED_NEEDS_HASH",
                            PasswordSalt = "SEED_NEEDS_HASH",
                            RegistrationDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "pivo_lover"
                        },
                        new
                        {
                            Id = 2,
                            AvatarUrl = "https://ui-avatars.com/api/?name=Marko+Horvat&background=D97706&color=fff",
                            Bio = "IPA entuzijast, traži nove craft pivovare",
                            Email = "marko@example.com",
                            FirstName = "Marko",
                            LastName = "Horvat",
                            PasswordHash = "SEED_NEEDS_HASH",
                            PasswordSalt = "SEED_NEEDS_HASH",
                            RegistrationDate = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "hop_king"
                        },
                        new
                        {
                            Id = 3,
                            AvatarUrl = "https://ui-avatars.com/api/?name=Ana+Novak&background=FCD34D&color=111",
                            Bio = "Ljubiteljica tamnih piva i europskih pivovara",
                            Email = "ana@example.com",
                            FirstName = "Ana",
                            LastName = "Novak",
                            PasswordHash = "SEED_NEEDS_HASH",
                            PasswordSalt = "SEED_NEEDS_HASH",
                            RegistrationDate = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "stout_fan"
                        },
                        new
                        {
                            Id = 4,
                            AvatarUrl = "https://ui-avatars.com/api/?name=Luka+Kovac&background=A16207&color=fff",
                            Bio = "Putujem svijetom u potrazi za savršenim pivom",
                            Email = "luka@example.com",
                            FirstName = "Luka",
                            LastName = "Kovač",
                            PasswordHash = "SEED_NEEDS_HASH",
                            PasswordSalt = "SEED_NEEDS_HASH",
                            RegistrationDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "craft_explorer"
                        });
                });

            modelBuilder.Entity("Cugger.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<double>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ulica 1, broj 10",
                            City = "Zagreb",
                            Country = "Hrvatska",
                            Latitude = 45.814999999999998,
                            Longitude = 15.981999999999999,
                            Name = "The Beer Garden"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Ilica 25",
                            City = "Zagreb",
                            Country = "Hrvatska",
                            Latitude = 45.816000000000003,
                            Longitude = 15.984999999999999,
                            Name = "Craft Beer Pub"
                        },
                        new
                        {
                            Id = 3,
                            Address = "O'Connell Street, broj 1",
                            City = "Dublin",
                            Country = "Irska",
                            Latitude = 53.348999999999997,
                            Longitude = -6.2599999999999998,
                            Name = "Irish Pub Dublin"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Tkalčićeva 36",
                            City = "Zagreb",
                            Country = "Hrvatska",
                            Latitude = 45.814999999999998,
                            Longitude = 15.978,
                            Name = "Mali Medo"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Ulica grada Vukovara 269",
                            City = "Zagreb",
                            Country = "Hrvatska",
                            Latitude = 45.798000000000002,
                            Longitude = 15.989000000000001,
                            Name = "Pivnica Pinta"
                        });
                });

            modelBuilder.Entity("Cugger.Models.Beer", b =>
                {
                    b.HasOne("Cugger.Models.Brewery", "Brewery")
                        .WithMany("Beers")
                        .HasForeignKey("BreweryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brewery");
                });

            modelBuilder.Entity("Cugger.Models.CheckIn", b =>
                {
                    b.HasOne("Cugger.Models.Beer", "Beer")
                        .WithMany("CheckIns")
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cugger.Models.User", "User")
                        .WithMany("CheckIns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cugger.Models.Venue", "Venue")
                        .WithMany("CheckIns")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Beer");

                    b.Navigation("User");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Cugger.Models.Friendship", b =>
                {
                    b.HasOne("Cugger.Models.User", "FromUser")
                        .WithMany("FromFriendships")
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cugger.Models.User", "ToUser")
                        .WithMany("ToFriendships")
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("Cugger.Models.Review", b =>
                {
                    b.HasOne("Cugger.Models.Beer", "Beer")
                        .WithMany("Reviews")
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cugger.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Beer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cugger.Models.Beer", b =>
                {
                    b.Navigation("CheckIns");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Cugger.Models.Brewery", b =>
                {
                    b.Navigation("Beers");
                });

            modelBuilder.Entity("Cugger.Models.User", b =>
                {
                    b.Navigation("CheckIns");

                    b.Navigation("FromFriendships");

                    b.Navigation("Reviews");

                    b.Navigation("ToFriendships");
                });

            modelBuilder.Entity("Cugger.Models.Venue", b =>
                {
                    b.Navigation("CheckIns");
                });
#pragma warning restore 612, 618
        }
    }
}
